### ISSUE TITLE
Display embed from flickr 

### ISSUE THREAD

**Issue by mariealine** [design-systems-france/website#31]
We host pictures of event on flickr
ex : [https://www.flickr.com/photos/designsystemsfrance/albums/72157706510316711](https://www.flickr.com/photos/designsystemsfrance/albums/72157706510316711)

Each album has possibility to be displayed as embed.

The idea is to display this embed like youtube and speakerdeck

**Comment by Kingeek** [comment]
The embed is unfortunately not responsive :/ Not sure it's a good idea though

**Comment by mariealine** [comment]
In the future we could have two format display according to the user's screen size, isn't ?
